apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: deployment-node-js
  name: deployment-node-js
spec:
  replicas: 3
  selector:
    matchLabels:
      app: deployment-node-js
  strategy: {}
  template:
    metadata:
      labels:
        app: deployment-node-js
    spec:
      containers:
      - name: nodejsdemo
        image: rxakash/nodejsdemo
        env:
          - name: PORT_NUMBER
            valueFrom:
              configMapKeyRef:
                name: my-config
                key: port_number
